ログイン機能実装（STEP1）
takamuu/obento_takeout_app pull request #31
Opened 2021-11-18 14:36 UTC by takamuu

## issue
close #29 

## 実装の目的と概要
-  ログイン機能実装工程をSTEP1とSTEP2に分割し、STEP1として実装
  - STEP1では、フロント側でJsonplaceholderを使用し、仮のユーザーIDのみで認証する仕組みを実装する

## 実装内容(技術的な点を記載)
- Inputボックスに入力された値を引数にJsonplaceholderのAPIを呼び出して、ログインボタンを押下した際、以下の動作・機能を実装
  - Inputボックスが空欄の場合はログインボタンを非活性とする
  - Inputボックスに該当しないユーザーIDを入力した場合はアラート表示＋ログインさせない
  - Inputボックスに該当するユーザーIDを入力した場合はホーム画面へ遷移

## 画像
- ログインボタンの動作

https://user-images.githubusercontent.com/42578729/142433078-4f693877-3d50-4de3-9bd8-169d3829a92a.mov

## 今後の学習課題や記録しておくこと
- STEP2で引き続き、ログイン機能実装 #6 
  - ユーザーIDをe-mailに変更する
  - passwordのInputボックスも合わせて判定する

## チェックリスト
- [ ] ローカル環境での動作確認をしたか（影響し得る範囲も含めて）
- [ ] GitHub で ファイル差分（Files changed）を確認し、内容が合っているか。不要なファイルに差分がでていないか

2021-11-18 15:21 UTC, fumi238000 requested changes
@takamuu 
axiosいい感じで使えていますね！
曖昧な部分あったら私も調べますので、プルリクに記載しておいてください！

- Inputボックスという表現はより、inputフォームの方が良いかもしれないです！(ググってみましたが、その表現だと出てこなかったです！)
- 私は`JSONPlaceholder`の仕様を理解しているので、idが11でログインできないことがわかりますが、知らない方が見た場合、その理由が分からないと思います。なので、現在の仕様で成功するidを記載しておきましょう！

2021-11-18 15:21 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +  const [loading, setLoading] = useState(false);
[質問]useStateには型指定はしない方針でしょうか？

2021-11-18 15:29 UTC, takamuu commented on frontend/src/components/pages/Login.tsx
> +            disabled={userId === ''}
inputフォームが空欄の時、非活性とする仕様です！

2021-11-18 15:32 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +  const [loading, setLoading] = useState(false);
useStateで型推論が働く時は型指定しない方針なので、useState('')やuseState(false)の時は、書かない予定です！

2021-11-18 15:50 UTC, fumi238000 commented on frontend/src/components/pages/Login.tsx
> +            disabled={userId === ''}
すみません。disabledのtureとfalseを勘違いしてました！

2021-11-18 16:13 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
この場合だと、`axios.get<User>`でデータ取得に成功した時に、thenメソッドが呼ばれます。例：users/999でもthenメソッドが呼ばれる
ですが、users/xxxの場合は、`axios.get<User>`が失敗するので、例外時の処理であるcatchメソッドがよばれます。という理解です。

jsprimerで言うと…
[Promise#then Promise#catch](https://jsprimer.net/basic/async/#:~:text=onRejected%20%E3%81%8C%E5%91%BC%E3%81%B0%E3%82%8C%E3%82%8B-,Promise,-%23then%E3%81%A8Promise)
理解、あってますでしょうか？

2021-11-18 16:16 UTC, takamuu commented
@fumi238000 
いつも、ご指摘ありがとうございます！
今慌てて、jsPrimer読み返していますが、理解が深まります。Promise（非同期処理）をやっている事とのリンクがすっかり抜けてしまっていました。もう一度、じっくり読みたいところですね〜！

2021-11-18 16:17 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
> この場合だと、axios.get<User>でデータ取得に成功した時に、thenメソッドが呼ばれます

だとすると、thenでres.dataを取得した時、elseの条件はどのような場合でしょうか？

2021-11-18 16:22 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
例えば、user/11の時は getに成功しても、dataの中に一致するユーザーIDはない。という状態と思います。

2021-11-18 16:24 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
訂正します！

2021-11-18 16:32 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
私も理解が浅くて申し訳ないです。
せっかくですので、`ユーザーが見つかりません`が表示されるパターンがあるかチェックしてみてください！

2021-11-18 19:05 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
axios.get<User>でデータ取得に成功　→　then
thenは２つの関数を引数にとるので、Promiseの状態がfulfilledであれば、resが取れているということなので、
if (res.data) {　←ここがtrueになる
　　非同期処理に成功
} else {　　←　Promiseの状態が、rejectedの場合は１つ目の関数resはfalseになるので、elseの処理に入る
　　非同期処理に失敗
}

この理解は合ってますでしょうか？

2021-11-18 19:43 UTC, takamuu commented on frontend/src/components/pages/Login.tsx
> +            disabled={userId === ''}
{ !userId }でも動作問題ないようです！修正します。

2021-11-19 00:58 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
### 1.試していただきたいこと
> せっかくですので、ユーザーが見つかりませんが表示されるパターンがあるかチェックしてみてください！

- 現在の仕様だと、elseの時に`ユーザーが見つかりません`が表示されるように実装されていると思います。
alertで表示できるか確認をしてください！（確かめたことをデータ化すると、より良いです）
- 何をどうすれば、自分の実装が確かなことを確認できるでしょうか？ぜひ自身でテストケースをいくつか想定して、その後テスト結果をメモしてみてください！（方法はお任せします）
```
例)
テスト項目 | 期待値 | 結果
id: 1を入力した時 | ログインできるが表示される | ○
id: 2を入力した時 |  ログインできるが表示される | ○
.
.
.
id:xの時 | ユーザーが見つかりませんが表示される | ○ 
id:xの時 | ユーザーが見つかりませんが表示される | ×  ←自分の期待と違う結果が出る = エラー箇所がわかる
```



 ### 2.認識について
- Primiseの状態で分岐をされているということですね！ 
- Promiseの状態がfulfilled, rejectedの状態はどのように確認できるでしょうか？

[ヒント]
thenはHTTPレスポンスが200, catchはHTTPレスポンスが200でない時に分岐します。自身で挙動を確かめてみてください！

2021-11-19 07:59 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
@fumi238000 
昨日、console.logで確認した結果としては、下記状態でした。
-  user/1 ~ user/10 だと、 status:200　→　then
-  user/(Inputフォームが空欄の状態) でも　status:200　→　then
-  user/1 ~ user/10 以外のURLだと、status:404　→　catch

なので、elseに入る方法はPromiseの取り出せない情報[Promiseの状態](https://jsprimer.net/basic/async/#promise-status)である、rejectedしかないと間違った結論で終了しましたが、

>[ヒント]
thenはHTTPレスポンスが200, catchはHTTPレスポンスが200でない時に分岐します。自身で挙動を確かめてみてください！

ご指摘頂いた内容で再度確認していると、rejectedになったなら、status:200以外というconsole.logの結果（status:404）と一致し、ようやく理解が降りてきました。

user/1 ~ user/10 のURLだと、 status:200　→　then
user/1 ~ user/10 以外のURLだと、status:404　→　catch

ここまでは正しく理解できていると考えています。
という前提であれば、elseに入るのは、user/1 ~ user/10までの指定に含まれるところをはじく設定に該当するものになるということなので、（わかりにくいので、具体例には）

`if (res.data)` に入ってきたパスの中で弾きたいIDを設定すればelseの分岐に入る。ので、
`if (res.data.id)`
にすると 
空欄でログインできてしまっていた、user/　というパスをはじくことができ、else分岐の「ユーザーが見つかりません」を表示することができました😭

2021-11-19 08:25 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
お疲れ様でした！
- `if (res.data)`はthenに分岐すれば必ず`true`になるので、elseに分岐しないことを理解するということでした！
- 今回はバックエンドが`JSONPlaceholder`で変更できないので、React側で分岐するしか方法はありませんが、今後はRailsAPI側でデータの分岐を行い、フロント側では、データを表示することだけにしてあげましょう！

2021-11-19 08:26 UTC, fumi238000 approved these changes

2021-11-19 08:30 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        .catch(() => alert('ログインできません'))
ありがとうございます！
記録に残しておきます！mm

2021-11-19 09:03 UTC, merged