[フロント]メッセージ表示機能実装
takamuu/obento_takeout_app pull request #33
Opened 2021-11-19 13:33 UTC by takamuu

## issue
close #32 

## 実装の目的と概要
-  ログイン画面のalert表示をメッセージ表示に変更する

## 実装内容(技術的な点を記載)
- chakra-ui toastを使用する
- custom hooksを作成する

## 画像（実装前後の比較など）
- 以下のパターンを動画内でテストしています
  - 何も入力していない状態でのログインボタン非活性
  - 不正なログインIDを入力した場合のメッセージ表記
  - 空欄を入力した場合のメッセージ表記
  - 正しいログインIDを入力した場合のメッセージ表記（id:1~10であればログイン可と設定）

https://user-images.githubusercontent.com/42578729/142629355-da8f29a7-3e5b-46d1-89cc-5e97449ad607.mov

## チェックリスト
- [ ] ローカル環境での動作確認をしたか（影響し得る範囲も含めて）
- [ ] GitHub で ファイル差分（Files changed）を確認し、内容が合っているか。不要なファイルに差分がでていないか

2021-11-19 14:04 UTC, fumi238000 requested changes
@takamuu 
お疲れ様です。カスタムフックいい感じですね！コメントしました！

2021-11-19 14:04 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +          if (res.data.id) {
先ほどもお伝えした通り、thenにはHTTP200の取得を想定しています。つまり、この中でエラー処理をするのは役割が違います。そのため、elseを用いてエラー処理を実行しない方が良いです。もしidが違うことを想定している場合は、それはRails側に処理を任せ、HTTP400を返すようにレスポンスを返すようにするのが良いと思います！

2021-11-19 14:51 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +            showMessage({ title: 'ログインしました', status: 'success' });
ここの改行についてですが、以下の改行の事でしょうか？

`showMessage({ title: 'ログインしました', status: 'success' });`
`showMessage({
              title: 'ユーザーが見つかりません',
              status: 'error',
            });`

一行に修正保存してみました。今、変更すると修正保存できたのですが、基本的には、保存時にvscodeが自動フォーマットをかけるに任せています。

2021-11-19 14:57 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          if (res.data.id) {
@fumi238000 
ありがとうございます！
thenの中のif文はじゃけぇさんの設計に沿った状態で、じゃけぇさんのuser_manegement_appの中でも、機能していない作り込みになっているので、外すべきかもしれませんが、じゃけぇさんの考えがあるのかも？と測りかねています。
あと、外す事に躊躇している理由は、inputフォームにスペースを入力するとログインできてしまう挙動になるためなのですが、どちらにしてもSTEP2で対応しなくてはいけないので、一旦コメントアウトしておくということでいかがでしょうか？

2021-11-19 14:58 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +        )
下欄でまとめさせて頂きますmm

2021-11-19 15:55 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +          if (res.data.id) {
>thenの中のif文はじゃけぇさんの設計に沿った状態で、じゃけぇさんのuser_manegement_appの中でも、機能していない作り込みになっているので、外すべきかもしれませんが、じゃけぇさんの考えがあるのかも？と図りかねています。

ここが曖昧だと後々響くので、@takamuuなりに判断して実装してみてください！

>あと、外す事に躊躇している理由は、inputフォームにスペースを入力するとログインできてしまう挙動になるためなのですが、STEP2ではなく、ここで対応したほうがよいでしょうか？

私も調べた結果、`/users/` + スペースだと配列が返ってきますね。今回はテストなので良いと思います！

[おまけ]
実際の挙動を考えた場合、スペースの場合ログインできないのが普通ですね。
jsonplaceholderを実際にRailsで実装すると、以下のように実装できるかと思います。
今後はバックエンドも実装しながら進めていくと思うので、この部分をイメージできることが大切です！
```rb
# 例 axios.get<User>(`https://jsonplaceholder.typicode.com/users/${id}`)

  def show
    if @user
      render json:  @user, status: :ok  # #=>これがthenに渡す値
    else
      render json: @user.errors,  status: :unprocessable_entity   #=>これがcatchに渡す値（スペースはこちら）
    end
  end

 def set_user
   @user = User.find_by(id: user_params[:id])  #=> idがスペースであった場合、@userに値は入らない
 end

 def user_params
   params.require(:user).permit(:id)
 end

```

2021-11-19 18:53 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          if (res.data.id) {
@fumi238000 
ありがとうございます！
Rails側のコードは、イメージできてなかったので、不安しかありませんでしたが、[おまけ]コードはすごい！わかりやすいです！！！
なるほど、見えるものが見えると、React側の条件分岐は不要と理解できましたので、削除します！mm

2021-11-21 03:26 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          showMessage({ title: 'ログインできません', status: 'error' })
@fumi238000 
ありがとうございます！
メッセージ内容を修正しました！

2021-11-21 03:29 UTC, fumi238000 commented on frontend/src/hooks/useAuth.ts
> +          showMessage({ title: 'ログインできません', status: 'error' })
@takamuu 
[コメント]
次回以降、私が再度見る必要がある場合は、`レビュー済`のラベルを外して、`レビュー依頼(佐藤)`を再度つけてコメントください！

2021-11-21 04:42 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          showMessage({ title: 'ログインできません', status: 'error' })
@fumi238000 
承知しました！

2021-11-22 09:17 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          showMessage({ title: 'ログインできません', status: 'error' })
@fumi238000 
お疲れさまです！
下欄に、Changes requestedと表示されていますが、全て解決済でよいでしょうか？

2021-11-22 09:20 UTC, fumi238000 approved these changes

2021-11-22 09:22 UTC, takamuu commented on frontend/src/hooks/useAuth.ts
> +          showMessage({ title: 'ログインできません', status: 'error' })
ありがとうございます！mm

2021-11-22 09:22 UTC, merged